# Imports

In [ ]:
import pandas as pd

In [ ]:
"""
h5py==2.10.0
jupyter==1.0.0
Keras==2.4.3
Keras-Preprocessing==1.1.2
numpy==1.19.5
pandas==1.2.4
scikit-learn==0.24.1
scipy==1.6.2
seaborn==0.11.1
tensorflow==2.4.1
torch==1.8.1
"""

'\nh5py==2.10.0\njupyter==1.0.0\nKeras==2.4.3\nKeras-Preprocessing==1.1.2\nnumpy==1.19.5\npandas==1.2.4\nscikit-learn==0.24.1\nscipy==1.6.2\nseaborn==0.11.1\ntensorflow==2.4.1\ntorch==1.8.1\n'

In [ ]:
!gdown --id "1TBxr27T0vdOagjDLvKlio-MDiWDpqHCb"   #ipl_csv2.zip
!gdown --id "1AN4kUrHQN72iDQFSwEwI6i7gbGJQ3LTr"   #submissionFormat.zip   
!gdown --id "1TCqabv-mePLDkj2qKIxQecCuB_ZwO4Gk"   #input_test_data.csv

Downloading...
From: https://drive.google.com/uc?id=1TBxr27T0vdOagjDLvKlio-MDiWDpqHCb
To: /content/ipl_csv2.zip
3.24MB [00:00, 102MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AN4kUrHQN72iDQFSwEwI6i7gbGJQ3LTr
To: /content/submissionFormat.zip
100% 1.00k/1.00k [00:00<00:00, 1.70MB/s]
Downloading...
From: https://drive.google.com/uc?id=1TCqabv-mePLDkj2qKIxQecCuB_ZwO4Gk
To: /content/input_test_data.csv
100% 193/193 [00:00<00:00, 316kB/s]

In [ ]:
!unzip /content/ipl_csv2.zip -d dataset
!unzip /content/submissionFormat.zip -d submission

Archive:  /content/ipl_csv2.zip
replace dataset/README.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: yA
  inflating: dataset/README.txt
  inflating: dataset/all_matches.csv
replace dataset/335982.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: yA
  inflating: dataset/335982.csv
replace dataset/335983.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: dataset/335983.csv
replace dataset/335984.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: dataset/335984.csv
  inflating: dataset/335986.csv
  inflating: dataset/335985.csv
  inflating: dataset/335987.csv
  inflating: dataset/335988.csv
  inflating: dataset/335989.csv
  inflating: dataset/335990.csv
  inflating: dataset/335991.csv
  inflating: dataset/335993.csv
  inflating: dataset/335992.csv
  inflating: dataset/335994.csv
  inflating: dataset/335995.csv
  inflating: dataset/335996.csv
  inflating: dataset/335997.csv
  inflating: dataset/335998.csv
  inflating: dataset/336000.csv
  inflating: dataset/335999.csv
  inflating: dataset/336001.csv
  inflating: dataset/336003.csv
  inflating: dataset/336034.csv
  inflating: dataset/336005.csv
  inflating: dataset/336004.csv
  inflating: dataset/336006.csv
  inflating: dataset/336007.csv
  inflating: dataset/336008.csv
  inflating: dataset/336009.csv
  inflating: dataset/336010.csv
  inflating: dataset/336011.csv
  inflating: dataset/336013.csv
  inflating: dataset/336014.csv
  inflating: dataset/336015.csv
  inflating: dataset/336016.csv
  inflating: dataset/336017.csv
  inflating: dataset/336018.csv
  inflating: dataset/336020.csv
  inflating: dataset/336021.csv
  inflating: dataset/336023.csv
  inflating: dataset/336022.csv
  inflating: dataset/336024.csv
  inflating: dataset/336025.csv
  inflating: dataset/336026.csv
  inflating: dataset/336027.csv
  inflating: dataset/336028.csv
  inflating: dataset/336029.csv
  inflating: dataset/336031.csv
  inflating: dataset/336032.csv
  inflating: dataset/336033.csv
  inflating: dataset/336002.csv
  inflating: dataset/336035.csv
  inflating: dataset/336036.csv
  inflating: dataset/336037.csv
  inflating: dataset/336012.csv
  inflating: dataset/336019.csv
  inflating: dataset/336038.csv
  inflating: dataset/336039.csv
  inflating: dataset/336040.csv
  inflating: dataset/392182.csv
  inflating: dataset/392181.csv
  inflating: dataset/392183.csv
  inflating: dataset/392184.csv
  inflating: dataset/392185.csv
  inflating: dataset/392186.csv
  inflating: dataset/392188.csv
  inflating: dataset/392189.csv
  inflating: dataset/392190.csv
  inflating: dataset/392191.csv
  inflating: dataset/392192.csv
  inflating: dataset/392194.csv
  inflating: dataset/392195.csv
  inflating: dataset/392196.csv
  inflating: dataset/392197.csv
  inflating: dataset/392198.csv
  inflating: dataset/392199.csv
  inflating: dataset/392200.csv
  inflating: dataset/392202.csv
  inflating: dataset/392201.csv
  inflating: dataset/392203.csv
  inflating: dataset/392204.csv
  inflating: dataset/392206.csv
  inflating: dataset/392205.csv
  inflating: dataset/392207.csv
  inflating: dataset/392208.csv
  inflating: dataset/392209.csv
  inflating: dataset/392210.csv
  inflating: dataset/392211.csv
  inflating: dataset/392212.csv
  inflating: dataset/392213.csv
  inflating: dataset/392214.csv
  inflating: dataset/392215.csv
  inflating: dataset/392217.csv
  inflating: dataset/392216.csv
  inflating: dataset/392219.csv
  inflating: dataset/392218.csv
  inflating: dataset/392220.csv
  inflating: dataset/392222.csv
  inflating: dataset/392221.csv
  inflating: dataset/392223.csv
  inflating: dataset/392225.csv
  inflating: dataset/392224.csv
  inflating: dataset/392226.csv
  inflating: dataset/392227.csv
  inflating: dataset/392228.csv
  inflating: dataset/392230.csv
  inflating: dataset/392229.csv
  inflating: dataset/392231.csv
  inflating: dataset/392232.csv
  inflating: dataset/392233.csv
  inflating: dataset/392234.csv
  inflating: dataset/392236.csv
  inflating: dataset/392235.csv
  inflating: dataset/392237.csv
  inflating: dataset/392238.csv
  inflating: dataset/392239.csv
  inflating: dataset/419106.csv
  inflating: dataset/419108.csv
  inflating: dataset/419107.csv
  inflating: dataset/419110.csv
  inflating: dataset/419109.csv
  inflating: dataset/419111.csv
  inflating: dataset/419112.csv
  inflating: dataset/419113.csv
  inflating: dataset/419114.csv
  inflating: dataset/419115.csv
  inflating: dataset/419116.csv
  inflating: dataset/419117.csv
  inflating: dataset/419118.csv
  inflating: dataset/419119.csv
  inflating: dataset/419120.csv
  inflating: dataset/419121.csv
  inflating: dataset/419122.csv
  inflating: dataset/419123.csv
  inflating: dataset/419124.csv
  inflating: dataset/419125.csv
  inflating: dataset/419128.csv
  inflating: dataset/419126.csv
  inflating: dataset/419127.csv
  inflating: dataset/419129.csv
  inflating: dataset/419130.csv
  inflating: dataset/419131.csv
  inflating: dataset/419132.csv
  inflating: dataset/419133.csv
  inflating: dataset/419134.csv
  inflating: dataset/419135.csv
  inflating: dataset/419136.csv
  inflating: dataset/419138.csv
  inflating: dataset/419137.csv
  inflating: dataset/419139.csv
  inflating: dataset/419140.csv
  inflating: dataset/419141.csv
  inflating: dataset/419142.csv
  inflating: dataset/419143.csv
  inflating: dataset/419144.csv
  inflating: dataset/419145.csv
  inflating: dataset/419146.csv
  inflating: dataset/419148.csv
  inflating: dataset/419147.csv
  inflating: dataset/419150.csv
  inflating: dataset/419149.csv
  inflating: dataset/419151.csv
  inflating: dataset/419153.csv
  inflating: dataset/419152.csv
  inflating: dataset/419154.csv
  inflating: dataset/419155.csv
  inflating: dataset/419156.csv
  inflating: dataset/419158.csv
  inflating: dataset/419157.csv
  inflating: dataset/419159.csv
  inflating: dataset/419160.csv
  inflating: dataset/419161.csv
  inflating: dataset/419162.csv
  inflating: dataset/419163.csv
  inflating: dataset/419164.csv
  inflating: dataset/419165.csv
  inflating: dataset/501198.csv
  inflating: dataset/501199.csv
  inflating: dataset/501200.csv
  inflating: dataset/501202.csv
  inflating: dataset/501201.csv
  inflating: dataset/501203.csv
  inflating: dataset/501204.csv
  inflating: dataset/501205.csv
  inflating: dataset/501207.csv
  inflating: dataset/501206.csv
  inflating: dataset/501208.csv
  inflating: dataset/501209.csv
  inflating: dataset/501210.csv
  inflating: dataset/501211.csv
  inflating: dataset/501212.csv
  inflating: dataset/501213.csv
  inflating: dataset/501214.csv
  inflating: dataset/501215.csv
  inflating: dataset/501216.csv
  inflating: dataset/501218.csv
  inflating: dataset/501219.csv
  inflating: dataset/501220.csv
  inflating: dataset/501222.csv
  inflating: dataset/501221.csv
  inflating: dataset/501223.csv
  inflating: dataset/501225.csv
  inflating: dataset/501224.csv
  inflating: dataset/501226.csv
  inflating: dataset/501227.csv
  inflating: dataset/501228.csv
  inflating: dataset/501229.csv
  inflating: dataset/501230.csv
  inflating: dataset/501232.csv
  inflating: dataset/501231.csv
  inflating: dataset/501233.csv
  inflating: dataset/501234.csv
  inflating: dataset/501236.csv
  inflating: dataset/501235.csv
  inflating: dataset/501237.csv
  inflating: dataset/501238.csv
  inflating: dataset/501239.csv
  inflating: dataset/501240.csv
  inflating: dataset/501241.csv
  inflating: dataset/501242.csv
  inflating: dataset/501243.csv
  inflating: dataset/501244.csv
  inflating: dataset/501245.csv
  inflating: dataset/501246.csv
  inflating: dataset/501248.csv
  inflating: dataset/501247.csv
  inflating: dataset/501249.csv
  inflating: dataset/501251.csv
  inflating: dataset/501250.csv
  inflating: dataset/501252.csv
  inflating: dataset/501253.csv
  inflating: dataset/501254.csv
  inflating: dataset/501256.csv
  inflating: dataset/501255.csv
  inflating: dataset/501257.csv
  inflating: dataset/501258.csv
  inflating: dataset/501259.csv
  inflating: dataset/501260.csv
  inflating: dataset/501261.csv
  inflating: dataset/501262.csv
  inflating: dataset/501263.csv
  inflating: dataset/501264.csv
  inflating: dataset/501265.csv
  inflating: dataset/501266.csv
  inflating: dataset/501267.csv
  inflating: dataset/501268.csv
  inflating: dataset/501269.csv
  inflating: dataset/501270.csv
  inflating: dataset/501271.csv
  inflating: dataset/548306.csv
  inflating: dataset/548307.csv
  inflating: dataset/548308.csv
  inflating: dataset/548309.csv
  inflating: dataset/548311.csv
  inflating: dataset/548310.csv
  inflating: dataset/548313.csv
  inflating: dataset/548312.csv
  inflating: dataset/548314.csv
  inflating: dataset/548315.csv
  inflating: dataset/548316.csv
  inflating: dataset/548317.csv
  inflating: dataset/548318.csv
  inflating: dataset/548319.csv
  inflating: dataset/548320.csv
  inflating: dataset/548322.csv
  inflating: dataset/548323.csv
  inflating: dataset/548324.csv
  inflating: dataset/548325.csv
  inflating: dataset/548326.csv
  inflating: dataset/548327.csv
  inflating: dataset/548328.csv
  inflating: dataset/548330.csv
  inflating: dataset/548321.csv
  inflating: dataset/548331.csv
  inflating: dataset/548333.csv
  inflating: dataset/548332.csv
  inflating: dataset/548335.csv
  inflating: dataset/548334.csv
  inflating: dataset/548336.csv
  inflating: dataset/548337.csv
  inflating: dataset/548339.csv
  inflating: dataset/548341.csv
  inflating: dataset/548342.csv
  inflating: dataset/548344.csv
  inflating: dataset/548343.csv
  inflating: dataset/548345.csv
  inflating: dataset/548346.csv
  inflating: dataset/548347.csv
  inflating: dataset/548349.csv
  inflating: dataset/548348.csv
  inflating: dataset/548350.csv
  inflating: dataset/548351.csv
  inflating: dataset/548352.csv
  inflating: dataset/548354.csv
  inflating: dataset/548353.csv
  inflating: dataset/548355.csv
  inflating: dataset/548356.csv
  inflating: dataset/548357.csv
  inflating: dataset/548359.csv
  inflating: dataset/548358.csv
  inflating: dataset/548360.csv
  inflating: dataset/548329.csv
  inflating: dataset/548361.csv
  inflating: dataset/548362.csv
  inflating: dataset/548364.csv
  inflating: dataset/548363.csv
  inflating: dataset/548366.csv
  inflating: dataset/548365.csv
  inflating: dataset/548367.csv
  inflating: dataset/548368.csv
  inflating: dataset/548369.csv
  inflating: dataset/548370.csv
  inflating: dataset/548372.csv
  inflating: dataset/548371.csv
  inflating: dataset/548373.csv
  inflating: dataset/548374.csv
  inflating: dataset/548375.csv
  inflating: dataset/548376.csv
  inflating: dataset/548377.csv
  inflating: dataset/548378.csv
  inflating: dataset/548379.csv
  inflating: dataset/548380.csv
  inflating: dataset/548381.csv
  inflating: dataset/597998.csv
  inflating: dataset/597999.csv
  inflating: dataset/598000.csv
  inflating: dataset/598001.csv
  inflating: dataset/598002.csv
  inflating: dataset/598004.csv
  inflating: dataset/598003.csv
  inflating: dataset/598005.csv
  inflating: dataset/598048.csv
  inflating: dataset/598006.csv
  inflating: dataset/598007.csv
  inflating: dataset/598008.csv
  inflating: dataset/598009.csv
  inflating: dataset/598010.csv
  inflating: dataset/598011.csv
  inflating: dataset/598012.csv
  inflating: dataset/598014.csv
  inflating: dataset/598013.csv
  inflating: dataset/598015.csv
  inflating: dataset/598016.csv
  inflating: dataset/598017.csv
  inflating: dataset/598018.csv
  inflating: dataset/598019.csv
  inflating: dataset/598020.csv
  inflating: dataset/598021.csv
  inflating: dataset/598023.csv
  inflating: dataset/598022.csv
  inflating: dataset/598024.csv
  inflating: dataset/598025.csv
  inflating: dataset/598026.csv
  inflating: dataset/598059.csv
  inflating: dataset/598027.csv
  inflating: dataset/598029.csv
  inflating: dataset/598030.csv
  inflating: dataset/598031.csv
  inflating: dataset/598032.csv
  inflating: dataset/598033.csv
  inflating: dataset/598035.csv
  inflating: dataset/598034.csv
  inflating: dataset/598037.csv
  inflating: dataset/598036.csv
  inflating: dataset/598038.csv
  inflating: dataset/598040.csv
  inflating: dataset/598039.csv
  inflating: dataset/598041.csv
  inflating: dataset/598042.csv
  inflating: dataset/598043.csv
  inflating: dataset/598044.csv
  inflating: dataset/598046.csv
  inflating: dataset/598047.csv
  inflating: dataset/598064.csv
  inflating: dataset/598049.csv
  inflating: dataset/598050.csv
  inflating: dataset/598051.csv
  inflating: dataset/598052.csv
  inflating: dataset/598053.csv
  inflating: dataset/598054.csv
  inflating: dataset/598055.csv
  inflating: dataset/598056.csv
  inflating: dataset/598058.csv
  inflating: dataset/598057.csv
  inflating: dataset/598060.csv
  inflating: dataset/598045.csv
  inflating: dataset/598062.csv
  inflating: dataset/598063.csv
  inflating: dataset/598061.csv
  inflating: dataset/598028.csv
  inflating: dataset/598065.csv
  inflating: dataset/598068.csv
  inflating: dataset/598066.csv
  inflating: dataset/598067.csv
  inflating: dataset/598069.csv
  inflating: dataset/598070.csv
  inflating: dataset/598071.csv
  inflating: dataset/598072.csv
  inflating: dataset/598073.csv
  inflating: dataset/729279.csv
  inflating: dataset/729281.csv
  inflating: dataset/729283.csv
  inflating: dataset/729285.csv
  inflating: dataset/729289.csv
  inflating: dataset/729287.csv
  inflating: dataset/729291.csv
  inflating: dataset/729293.csv
  inflating: dataset/729295.csv
  inflating: dataset/729297.csv
  inflating: dataset/729299.csv
  inflating: dataset/729303.csv
  inflating: dataset/729301.csv
  inflating: dataset/729307.csv
  inflating: dataset/729305.csv
  inflating: dataset/729309.csv
  inflating: dataset/729311.csv
  inflating: dataset/729313.csv
  inflating: dataset/729315.csv
  inflating: dataset/729317.csv
  inflating: dataset/733971.csv
  inflating: dataset/733973.csv
  inflating: dataset/733975.csv
  inflating: dataset/733977.csv
  inflating: dataset/733981.csv
  inflating: dataset/733979.csv
  inflating: dataset/733983.csv
  inflating: dataset/733985.csv
  inflating: dataset/733987.csv
  inflating: dataset/733989.csv
  inflating: dataset/733991.csv
  inflating: dataset/733995.csv
  inflating: dataset/733993.csv
  inflating: dataset/733999.csv
  inflating: dataset/733997.csv
  inflating: dataset/734001.csv
  inflating: dataset/734003.csv
  inflating: dataset/734005.csv
  inflating: dataset/734009.csv
  inflating: dataset/734007.csv
  inflating: dataset/734011.csv
  inflating: dataset/734015.csv
  inflating: dataset/734013.csv
  inflating: dataset/734019.csv
  inflating: dataset/734017.csv
  inflating: dataset/734021.csv
  inflating: dataset/734023.csv
  inflating: dataset/734025.csv
  inflating: dataset/734029.csv
  inflating: dataset/734027.csv
  inflating: dataset/734031.csv
  inflating: dataset/734033.csv
  inflating: dataset/734035.csv
  inflating: dataset/734037.csv
  inflating: dataset/734041.csv
  inflating: dataset/734039.csv
  inflating: dataset/734043.csv
  inflating: dataset/734045.csv
  inflating: dataset/734047.csv
  inflating: dataset/734049.csv
  inflating: dataset/829733.csv
  inflating: dataset/829735.csv
  inflating: dataset/829737.csv
  inflating: dataset/829739.csv
  inflating: dataset/829741.csv
  inflating: dataset/829743.csv
  inflating: dataset/829745.csv
  inflating: dataset/829747.csv
  inflating: dataset/829749.csv
  inflating: dataset/829705.csv
  inflating: dataset/829707.csv
  inflating: dataset/829709.csv
  inflating: dataset/829713.csv
  inflating: dataset/829711.csv
  inflating: dataset/829715.csv
  inflating: dataset/829717.csv
  inflating: dataset/829719.csv
  inflating: dataset/829721.csv
  inflating: dataset/829725.csv
  inflating: dataset/829727.csv
  inflating: dataset/829729.csv
  inflating: dataset/829731.csv
  inflating: dataset/829751.csv
  inflating: dataset/829753.csv
  inflating: dataset/829757.csv
  inflating: dataset/829759.csv
  inflating: dataset/829765.csv
  inflating: dataset/829723.csv
  inflating: dataset/829763.csv
  inflating: dataset/829767.csv
  inflating: dataset/829769.csv
  inflating: dataset/829771.csv
  inflating: dataset/829773.csv
  inflating: dataset/829775.csv
  inflating: dataset/829777.csv
  inflating: dataset/829779.csv
  inflating: dataset/829781.csv
  inflating: dataset/829783.csv
  inflating: dataset/829785.csv
  inflating: dataset/829787.csv
  inflating: dataset/829761.csv
  inflating: dataset/829789.csv
  inflating: dataset/829791.csv
  inflating: dataset/829793.csv
  inflating: dataset/829795.csv
  inflating: dataset/829797.csv
  inflating: dataset/829799.csv
  inflating: dataset/829801.csv
  inflating: dataset/829803.csv
  inflating: dataset/829805.csv
  inflating: dataset/829807.csv
  inflating: dataset/829809.csv
  inflating: dataset/829811.csv
  inflating: dataset/829813.csv
  inflating: dataset/829815.csv
  inflating: dataset/829817.csv
  inflating: dataset/829819.csv
  inflating: dataset/829821.csv
  inflating: dataset/829823.csv
  inflating: dataset/980901.csv
  inflating: dataset/980903.csv
  inflating: dataset/980905.csv
  inflating: dataset/980907.csv
  inflating: dataset/980909.csv
  inflating: dataset/980911.csv
  inflating: dataset/980913.csv
  inflating: dataset/980915.csv
  inflating: dataset/980917.csv
  inflating: dataset/980919.csv
  inflating: dataset/980921.csv
  inflating: dataset/980923.csv
  inflating: dataset/980925.csv
  inflating: dataset/980927.csv
  inflating: dataset/980929.csv
  inflating: dataset/980931.csv
  inflating: dataset/980933.csv
  inflating: dataset/980935.csv
  inflating: dataset/980937.csv
  inflating: dataset/980939.csv
  inflating: dataset/980941.csv
  inflating: dataset/980943.csv
  inflating: dataset/980945.csv
  inflating: dataset/980947.csv
  inflating: dataset/980949.csv
  inflating: dataset/980951.csv
  inflating: dataset/980953.csv
  inflating: dataset/980955.csv
  inflating: dataset/980957.csv
  inflating: dataset/980959.csv
  inflating: dataset/980961.csv
  inflating: dataset/980963.csv
  inflating: dataset/980965.csv
  inflating: dataset/980967.csv
  inflating: dataset/980969.csv
  inflating: dataset/980971.csv
  inflating: dataset/980973.csv
  inflating: dataset/980975.csv
  inflating: dataset/980977.csv
  inflating: dataset/980979.csv
  inflating: dataset/980981.csv
  inflating: dataset/980983.csv
  inflating: dataset/980985.csv
  inflating: dataset/980987.csv
  inflating: dataset/980989.csv
  inflating: dataset/980991.csv
  inflating: dataset/980993.csv
  inflating: dataset/980995.csv
  inflating: dataset/980997.csv
  inflating: dataset/980999.csv
  inflating: dataset/981001.csv
  inflating: dataset/981003.csv
  inflating: dataset/981005.csv
  inflating: dataset/981007.csv
  inflating: dataset/981009.csv
  inflating: dataset/981011.csv
  inflating: dataset/981013.csv
  inflating: dataset/981015.csv
  inflating: dataset/981017.csv
  inflating: dataset/981019.csv
  inflating: dataset/1082591.csv
  inflating: dataset/1082592.csv
  inflating: dataset/1082593.csv
  inflating: dataset/1082595.csv
  inflating: dataset/1082594.csv
  inflating: dataset/1082596.csv
  inflating: dataset/1082597.csv
  inflating: dataset/1082598.csv
  inflating: dataset/1082599.csv
  inflating: dataset/1082600.csv
  inflating: dataset/1082601.csv
  inflating: dataset/1082602.csv
  inflating: dataset/1082603.csv
  inflating: dataset/1082604.csv
  inflating: dataset/1082605.csv
  inflating: dataset/1082606.csv
  inflating: dataset/1082607.csv
  inflating: dataset/1082608.csv
  inflating: dataset/1082609.csv
  inflating: dataset/1082610.csv
  inflating: dataset/1082611.csv
  inflating: dataset/1082612.csv
  inflating: dataset/1082613.csv
  inflating: dataset/1082614.csv
  inflating: dataset/1082615.csv
  inflating: dataset/1082616.csv
  inflating: dataset/1082617.csv
  inflating: dataset/1082618.csv
  inflating: dataset/1082620.csv
  inflating: dataset/1082621.csv
  inflating: dataset/1082622.csv
  inflating: dataset/1082623.csv
  inflating: dataset/1082624.csv
  inflating: dataset/1082625.csv
  inflating: dataset/1082626.csv

In [ ]:
!mv /content/dataset/all_matches.csv .

In [ ]:
df = pd.read_csv('all_matches.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [ ]:
df.shape

(194354, 22)

# Preprocessing

In [ ]:
df.isnull().sum()

match_id                       0
season                         0
start_date                     0
venue                          0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                     188470
noballs                   193580
byes                      193843
legbyes                   191236
penalty                   194352
wicket_type               184794
player_dismissed          184794
other_wicket_type         194354
other_player_dismissed    194354
dtype: int64

In [ ]:
df = df.drop(columns=['other_player_dismissed','other_wicket_type','penalty'])

In [ ]:
df.isnull().sum()

match_id                 0
season                   0
start_date               0
venue                    0
innings                  0
ball                     0
batting_team             0
bowling_team             0
striker                  0
non_striker              0
bowler                   0
runs_off_bat             0
extras                   0
wides               188470
noballs             193580
byes                193843
legbyes             191236
wicket_type         184794
player_dismissed    184794
dtype: int64

In [ ]:
df = df.drop(index = list(range(176428,176443)))
df = df.drop(index = list(range(57068,57131)))
df = df.drop(index = list(range(115599,115727)))

In [ ]:
df['byes'] = df['byes'].fillna(0)
df['noballs'] = df['noballs'].fillna(0)
df['wides'] = df['wides'].fillna(0)
df['legbyes'] = df['legbyes'].fillna(0)
df['player_dismissed'] = df['player_dismissed'].fillna('notout')
df['wicket_type'] = df['wicket_type'].fillna('nowicket')

In [ ]:
df = df.replace(['M Chinnaswamy Stadium',"M.Chinnaswamy Stadium"],"M Chinnaswamy Stadium")
df = df.replace(['MA Chidambaram Stadium, Chepauk',"MA Chidambaram Stadium, Chepauk, Chennai"],"MA Chidambaram Stadium")
df = df.replace(['Punjab Cricket Association IS Bindra Stadium',"Punjab Cricket Association Stadium, Mohali"],"Punjab Cricket Association Stadium, Mohali")
df = df.replace(['Wankhede Stadium',"Wankhede Stadium, Mumbai","Maharashtra Cricket Association Stadium"],"Wankhede Stadium")
df = df.replace(['Rajiv Gandhi International Stadium, Uppal',"Rajiv Gandhi International Stadium"],"Rajiv Gandhi International Stadium")
df = df.replace(['Rajiv Gandhi International Stadium, Uppal',"Rajiv Gandhi International Stadium"],"Rajiv Gandhi International Stadium")
df = df.replace(['Delhi Daredevils'],"Delhi Capitals")
df = df.replace(['Deccan Chargers'],"Sunrisers Hyderabad")
df = df.replace(['Rising Pune Supergiant'],'Rising Pune Supergiants')
df = df.replace(["Punjab Cricket Association IS Bindra Stadium, Mohali","Punjab Cricket Association IS Bindra Stadium","Punjab Cricket Association Stadium, Mohali"],"Punjab Cricket Association Stadium, Mohali")

In [ ]:
df['season'].astype(str)
df = df.replace(['2007/08'],'2008')
df = df.replace(['2009/10'],'2010')
df = df.replace(['2020/21'],'2020')
df = df.replace([2012],'2012')
df = df.replace([2018],'2018')
df = df.replace([2019],'2019')
df = df.replace([2013],'2013')
df = df.replace([2014],'2014')
df = df.replace([2015],'2015')
df = df.replace([2016],'2016')
df = df.replace([2017],'2017')
df['season'].astype(str)

0         2008
1         2008
2         2008
3         2008
4         2008
          ...
194349    2021
194350    2021
194351    2021
194352    2021
194353    2021
Name: season, Length: 194148, dtype: object

In [ ]:
len(df[df['season']==2018]['match_id'].unique())

0

# EDA

In [ ]:
df

        match_id season  start_date  ... legbyes  wicket_type  player_dismissed
0         335982   2008  2008-04-18  ...     1.0     nowicket            notout
1         335982   2008  2008-04-18  ...     0.0     nowicket            notout
2         335982   2008  2008-04-18  ...     0.0     nowicket            notout
3         335982   2008  2008-04-18  ...     0.0     nowicket            notout
4         335982   2008  2008-04-18  ...     0.0     nowicket            notout
...          ...    ...         ...  ...     ...          ...               ...
194349   1254060   2021  2021-04-11  ...     0.0     nowicket            notout
194350   1254060   2021  2021-04-11  ...     0.0     nowicket            notout
194351   1254060   2021  2021-04-11  ...     0.0     nowicket            notout
194352   1254060   2021  2021-04-11  ...     0.0     nowicket            notout
194353   1254060   2021  2021-04-11  ...     0.0     nowicket            notout

[194148 rows x 19 columns]

In [ ]:
powerplay

        match_id season  start_date  ... legbyes  wicket_type  player_dismissed
150460   1175356   2019  2019-03-23  ...     0.0     nowicket            notout
150461   1175356   2019  2019-03-23  ...     0.0     nowicket            notout
150462   1175356   2019  2019-03-23  ...     0.0     nowicket            notout
150463   1175356   2019  2019-03-23  ...     0.0     nowicket            notout
150464   1175356   2019  2019-03-23  ...     0.0     nowicket            notout
...          ...    ...         ...  ...     ...          ...               ...
193536   1237181   2020  2020-11-10  ...     0.0     nowicket            notout
193537   1237181   2020  2020-11-10  ...     0.0     nowicket            notout
193538   1237181   2020  2020-11-10  ...     0.0     nowicket            notout
193539   1237181   2020  2020-11-10  ...     0.0     nowicket            notout
193540   1237181   2020  2020-11-10  ...     0.0     nowicket            notout

[13321 rows x 19 columns]

In [ ]:
#powerplay = df[(df['ball'] < 6.0) & (df['innings']<3)]
powerplay1 = df[(df['season'] == '2018') | (df['season'] == '2019') | (df['season'] == '2020')]
powerplay=powerplay1[(powerplay1['ball'] < 6.0) & (powerplay1['innings'] < 3)]

In [ ]:
powerplay['season'].unique()

array(['2019', '2018', '2020'], dtype=object)

In [ ]:
powerplay.shape

(13321, 19)

# Dataset Creation

In [ ]:
features = pd.DataFrame(columns=['match_id','venue','innings','batting_team','bowling_team','batsmen','bowlers','ppruns','wickets'])

In [ ]:
match=powerplay['match_id'].unique()

In [ ]:
for i in match:
  runs=powerplay[(powerplay['match_id']==i) & (powerplay['innings']==1)]['runs_off_bat'].sum() + powerplay[(powerplay['match_id']==i) & (powerplay['innings']==1)]['extras'].sum()
  wick=len(powerplay[(powerplay['match_id']==i) & (powerplay['player_dismissed']!='notout') & (powerplay['innings']==1)])
  runs1=powerplay[(powerplay['match_id']==i) & (powerplay['innings']==2)]['runs_off_bat'].sum() + powerplay[(powerplay['match_id']==i) & (powerplay['innings']==1)]['extras'].sum()
  wick1=len(powerplay[(powerplay['match_id']==i) & (powerplay['player_dismissed']!='notout') & (powerplay['innings']==2)])
  venue=powerplay[(powerplay['match_id']==i)]['venue'].unique()[0]
  batting_team1 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 1)]['batting_team'].unique()[0]
  bowling_team1 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 1)]['bowling_team'].unique()[0]
  batting_team2 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 2)]['batting_team'].unique()[0]
  bowling_team2 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 2)]['bowling_team'].unique()[0]
  batsmen1 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 1)]['striker'].unique()
  bowlers1 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 1)]['bowler'].unique()
  batsmen2 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 2)]['striker'].unique()
  bowlers2 = powerplay[(powerplay['match_id'] == i) &(powerplay['innings'] == 2)]['bowler'].unique()
  print(venue,powerplay[(powerplay['match_id']==i) & (powerplay['innings']==1)]['batting_team'].unique(),1, runs,wick)
  print(venue,powerplay[(powerplay['match_id']==i) & (powerplay['innings']==2)]['batting_team'].unique(),2, runs1,wick1)
  features = features.append({'match_id':i,'venue':venue,'innings':1,'batting_team':batting_team1,'bowling_team':bowling_team1,'batsmen':batsmen1,'bowlers':bowlers1,'ppruns':runs,'wickets':wick}, ignore_index=True)
  features = features.append({'match_id':i,'venue':venue,'innings':2,'batting_team':batting_team2,'bowling_team':bowling_team2,'batsmen':batsmen2,'bowlers':bowlers2,'ppruns':runs1,'wickets':wick1}, ignore_index=True)

MA Chidambaram Stadium ['Royal Challengers Bangalore'] 1 33 2
MA Chidambaram Stadium ['Chennai Super Kings'] 2 17 1
Eden Gardens ['Sunrisers Hyderabad'] 1 54 0
Eden Gardens ['Kolkata Knight Riders'] 2 51 1
Wankhede Stadium ['Delhi Capitals'] 1 45 2
Wankhede Stadium ['Mumbai Indians'] 2 46 3
Sawai Mansingh Stadium ['Kings XI Punjab'] 1 32 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 67 0
Arun Jaitley Stadium ['Delhi Capitals'] 1 43 1
Arun Jaitley Stadium ['Chennai Super Kings'] 2 56 1
Eden Gardens ['Kolkata Knight Riders'] 1 53 2
Eden Gardens ['Kings XI Punjab'] 2 50 2
M Chinnaswamy Stadium ['Mumbai Indians'] 1 52 0
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 2 60 1
Rajiv Gandhi International Stadium ['Rajasthan Royals'] 1 35 1
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 69 0
Punjab Cricket Association Stadium, Mohali ['Mumbai Indians'] 1 62 1
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 2 38 0
Arun Jaitley Stadium ['Kolkata Knight Riders'] 1 36 2
Arun Jaitley Stadium ['Delhi Capitals'] 2 45 1
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 1 59 0
Rajiv Gandhi International Stadium ['Royal Challengers Bangalore'] 2 26 3
MA Chidambaram Stadium ['Chennai Super Kings'] 1 29 3
MA Chidambaram Stadium ['Rajasthan Royals'] 2 42 3
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 1 54 2
Punjab Cricket Association Stadium, Mohali ['Delhi Capitals'] 2 44 1
Sawai Mansingh Stadium ['Royal Challengers Bangalore'] 1 48 0
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 52 0
Wankhede Stadium ['Mumbai Indians'] 1 40 1
Wankhede Stadium ['Chennai Super Kings'] 2 34 3
Arun Jaitley Stadium ['Delhi Capitals'] 1 36 2
Arun Jaitley Stadium ['Sunrisers Hyderabad'] 2 54 0
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 53 0
M Chinnaswamy Stadium ['Kolkata Knight Riders'] 2 52 1
MA Chidambaram Stadium ['Chennai Super Kings'] 1 54 0
MA Chidambaram Stadium ['Kings XI Punjab'] 2 46 2
Rajiv Gandhi International Stadium ['Mumbai Indians'] 1 30 2
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 37 2
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 40 2
M Chinnaswamy Stadium ['Delhi Capitals'] 2 49 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 28 1
Sawai Mansingh Stadium ['Kolkata Knight Riders'] 2 63 0
Punjab Cricket Association Stadium, Mohali ['Sunrisers Hyderabad'] 1 27 1
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 2 46 1
MA Chidambaram Stadium ['Kolkata Knight Riders'] 1 29 4
MA Chidambaram Stadium ['Chennai Super Kings'] 2 40 2
Wankhede Stadium ['Kings XI Punjab'] 1 50 0
Wankhede Stadium ['Mumbai Indians'] 2 50 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 54 3
Sawai Mansingh Stadium ['Chennai Super Kings'] 2 30 4
Eden Gardens ['Kolkata Knight Riders'] 1 41 1
Eden Gardens ['Delhi Capitals'] 2 58 2
Wankhede Stadium ['Mumbai Indians'] 1 57 0
Wankhede Stadium ['Rajasthan Royals'] 2 58 0
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 1 60 0
Punjab Cricket Association Stadium, Mohali ['Royal Challengers Bangalore'] 2 63 1
Eden Gardens ['Kolkata Knight Riders'] 1 49 1
Eden Gardens ['Chennai Super Kings'] 2 48 2
Rajiv Gandhi International Stadium ['Delhi Capitals'] 1 51 2
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 41 0
Wankhede Stadium ['Royal Challengers Bangalore'] 1 45 1
Wankhede Stadium ['Mumbai Indians'] 2 70 0
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 1 39 1
Punjab Cricket Association Stadium, Mohali ['Rajasthan Royals'] 2 50 1
Rajiv Gandhi International Stadium ['Chennai Super Kings'] 1 41 0
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 70 1
Wankhede Stadium ['Mumbai Indians'] 1 39 2
Wankhede Stadium ['Chennai Super Kings'] 2 43 2
Punjab Cricket Association Stadium, Mohali ['Delhi Capitals'] 1 45 1
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 2 76 2
Eden Gardens ['Royal Challengers Bangalore'] 1 52 1
Eden Gardens ['Kolkata Knight Riders'] 2 70 2
Rajiv Gandhi International Stadium ['Rajasthan Royals'] 1 48 1
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 57 1
MA Chidambaram Stadium ['Kolkata Knight Riders'] 1 64 2
MA Chidambaram Stadium ['Chennai Super Kings'] 2 76 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 51 2
Sawai Mansingh Stadium ['Delhi Capitals'] 2 57 4
Rajiv Gandhi International Stadium ['Mumbai Indians'] 1 54 3
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 60 0
M Chinnaswamy Stadium ['Kings XI Punjab'] 1 50 3
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 2 41 2
Wankhede Stadium ['Mumbai Indians'] 1 84 0
Wankhede Stadium ['Delhi Capitals'] 2 59 1
Eden Gardens ['Kolkata Knight Riders'] 1 49 1
Eden Gardens ['Sunrisers Hyderabad'] 2 42 2
M Chinnaswamy Stadium ['Rajasthan Royals'] 1 52 1
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 2 67 1
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 1 75 0
Punjab Cricket Association Stadium, Mohali ['Chennai Super Kings'] 2 49 2
Eden Gardens ['Kolkata Knight Riders'] 1 50 1
Eden Gardens ['Delhi Capitals'] 2 49 3
Wankhede Stadium ['Mumbai Indians'] 1 60 2
Wankhede Stadium ['Royal Challengers Bangalore'] 2 64 2
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 48 0
Sawai Mansingh Stadium ['Kolkata Knight Riders'] 2 54 1
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 1 49 0
Punjab Cricket Association Stadium, Mohali ['Sunrisers Hyderabad'] 2 42 3
Wankhede Stadium ['Chennai Super Kings'] 1 69 1
Wankhede Stadium ['Rajasthan Royals'] 2 34 3
Eden Gardens ['Kolkata Knight Riders'] 1 50 1
Eden Gardens ['Kings XI Punjab'] 2 75 0
M Chinnaswamy Stadium ['Delhi Capitals'] 1 28 2
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 2 45 2
Rajiv Gandhi International Stadium ['Chennai Super Kings'] 1 27 1
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 40 3
Sawai Mansingh Stadium ['Mumbai Indians'] 1 43 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 43 2
Arun Jaitley Stadium ['Kings XI Punjab'] 1 51 2
Arun Jaitley Stadium ['Delhi Capitals'] 2 45 3
Wankhede Stadium ['Sunrisers Hyderabad'] 1 51 4
Wankhede Stadium ['Mumbai Indians'] 2 31 3
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 52 1
M Chinnaswamy Stadium ['Chennai Super Kings'] 2 54 2
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 1 37 3
Rajiv Gandhi International Stadium ['Kings XI Punjab'] 2 46 0
Arun Jaitley Stadium ['Delhi Capitals'] 1 57 0
Arun Jaitley Stadium ['Kolkata Knight Riders'] 2 51 4
Wankhede Stadium ['Chennai Super Kings'] 1 51 1
Wankhede Stadium ['Mumbai Indians'] 2 49 0
Sawai Mansingh Stadium ['Sunrisers Hyderabad'] 1 39 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 43 1
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 40 0
M Chinnaswamy Stadium ['Kolkata Knight Riders'] 2 52 0
Wankhede Stadium ['Chennai Super Kings'] 1 56 0
Wankhede Stadium ['Delhi Capitals'] 2 59 2
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 43 1
M Chinnaswamy Stadium ['Mumbai Indians'] 2 35 3
Arun Jaitley Stadium ['Delhi Capitals'] 1 62 1
Arun Jaitley Stadium ['Rajasthan Royals'] 2 77 0
Eden Gardens ['Chennai Super Kings'] 1 57 1
Eden Gardens ['Kolkata Knight Riders'] 2 54 2
Holkar Cricket Stadium ['Kings XI Punjab'] 1 49 0
Holkar Cricket Stadium ['Mumbai Indians'] 2 40 1
Wankhede Stadium ['Royal Challengers Bangalore'] 1 47 1
Wankhede Stadium ['Chennai Super Kings'] 2 44 1
Rajiv Gandhi International Stadium ['Delhi Capitals'] 1 60 1
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 59 0
Wankhede Stadium ['Mumbai Indians'] 1 56 0
Wankhede Stadium ['Kolkata Knight Riders'] 2 42 2
Holkar Cricket Stadium ['Rajasthan Royals'] 1 45 2
Holkar Cricket Stadium ['Kings XI Punjab'] 2 38 2
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 1 38 2
Rajiv Gandhi International Stadium ['Royal Challengers Bangalore'] 2 57 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 63 1
Sawai Mansingh Stadium ['Kings XI Punjab'] 2 33 3
Eden Gardens ['Mumbai Indians'] 1 47 1
Eden Gardens ['Kolkata Knight Riders'] 2 47 2
Arun Jaitley Stadium ['Delhi Capitals'] 1 38 2
Arun Jaitley Stadium ['Sunrisers Hyderabad'] 2 51 1
Sawai Mansingh Stadium ['Chennai Super Kings'] 1 55 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 60 2
Holkar Cricket Stadium ['Kolkata Knight Riders'] 1 59 1
Holkar Cricket Stadium ['Kings XI Punjab'] 2 57 2
Arun Jaitley Stadium ['Delhi Capitals'] 1 44 2
Arun Jaitley Stadium ['Royal Challengers Bangalore'] 2 56 2
Wankhede Stadium ['Sunrisers Hyderabad'] 1 29 1
Wankhede Stadium ['Chennai Super Kings'] 2 56 0
Wankhede Stadium ['Mumbai Indians'] 1 51 0
Wankhede Stadium ['Rajasthan Royals'] 2 46 1
Holkar Cricket Stadium ['Kings XI Punjab'] 1 47 3
Holkar Cricket Stadium ['Royal Challengers Bangalore'] 2 65 0
Eden Gardens ['Rajasthan Royals'] 1 68 1
Eden Gardens ['Kolkata Knight Riders'] 2 51 2
Wankhede Stadium ['Mumbai Indians'] 1 60 3
Wankhede Stadium ['Kings XI Punjab'] 2 59 1
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 44 2
M Chinnaswamy Stadium ['Sunrisers Hyderabad'] 2 56 1
Arun Jaitley Stadium ['Delhi Capitals'] 1 39 1
Arun Jaitley Stadium ['Chennai Super Kings'] 2 47 0
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 45 1
Sawai Mansingh Stadium ['Royal Challengers Bangalore'] 2 54 1
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 1 60 0
Rajiv Gandhi International Stadium ['Kolkata Knight Riders'] 2 70 1
Arun Jaitley Stadium ['Delhi Capitals'] 1 46 2
Arun Jaitley Stadium ['Mumbai Indians'] 2 58 1
Wankhede Stadium ['Kings XI Punjab'] 1 29 3
Wankhede Stadium ['Chennai Super Kings'] 2 34 3
Wankhede Stadium ['Sunrisers Hyderabad'] 1 47 3
Wankhede Stadium ['Chennai Super Kings'] 2 32 3
Eden Gardens ['Kolkata Knight Riders'] 1 46 3
Eden Gardens ['Rajasthan Royals'] 2 57 1
Eden Gardens ['Sunrisers Hyderabad'] 1 45 0
Eden Gardens ['Kolkata Knight Riders'] 2 67 1
Wankhede Stadium ['Sunrisers Hyderabad'] 1 42 1
Wankhede Stadium ['Chennai Super Kings'] 2 36 1
Arun Jaitley Stadium ['Mumbai Indians'] 1 57 0
Arun Jaitley Stadium ['Delhi Capitals'] 2 50 0
Eden Gardens ['Royal Challengers Bangalore'] 1 42 1
Eden Gardens ['Kolkata Knight Riders'] 2 35 3
Sawai Mansingh Stadium ['Mumbai Indians'] 1 46 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 61 1
Arun Jaitley Stadium ['Kings XI Punjab'] 1 50 2
Arun Jaitley Stadium ['Delhi Capitals'] 2 60 1
Rajiv Gandhi International Stadium ['Kolkata Knight Riders'] 1 61 2
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 2 69 0
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 49 1
M Chinnaswamy Stadium ['Chennai Super Kings'] 2 27 4
Sawai Mansingh Stadium ['Rajasthan Royals'] 1 52 1
Sawai Mansingh Stadium ['Delhi Capitals'] 2 59 0
MA Chidambaram Stadium ['Sunrisers Hyderabad'] 1 54 1
MA Chidambaram Stadium ['Chennai Super Kings'] 2 51 1
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 70 1
M Chinnaswamy Stadium ['Kings XI Punjab'] 2 70 1
Eden Gardens ['Kolkata Knight Riders'] 1 32 2
Eden Gardens ['Rajasthan Royals'] 2 60 1
MA Chidambaram Stadium ['Mumbai Indians'] 1 45 1
MA Chidambaram Stadium ['Chennai Super Kings'] 2 41 3
Sawai Mansingh Stadium ['Sunrisers Hyderabad'] 1 51 1
Sawai Mansingh Stadium ['Rajasthan Royals'] 2 62 0
Arun Jaitley Stadium ['Delhi Capitals'] 1 59 1
Arun Jaitley Stadium ['Royal Challengers Bangalore'] 2 63 1
Eden Gardens ['Kolkata Knight Riders'] 1 50 0
Eden Gardens ['Mumbai Indians'] 2 40 2
Rajiv Gandhi International Stadium ['Sunrisers Hyderabad'] 1 77 0
Rajiv Gandhi International Stadium ['Kings XI Punjab'] 2 53 1
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 1 62 7
M Chinnaswamy Stadium ['Rajasthan Royals'] 2 13 0
MA Chidambaram Stadium ['Chennai Super Kings'] 1 27 1
MA Chidambaram Stadium ['Delhi Capitals'] 2 60 2
Wankhede Stadium ['Mumbai Indians'] 1 44 1
Wankhede Stadium ['Sunrisers Hyderabad'] 2 59 2
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 1 41 2
Punjab Cricket Association Stadium, Mohali ['Kolkata Knight Riders'] 2 61 1
Arun Jaitley Stadium ['Rajasthan Royals'] 1 30 4
Arun Jaitley Stadium ['Delhi Capitals'] 2 43 2
M Chinnaswamy Stadium ['Sunrisers Hyderabad'] 1 52 1
M Chinnaswamy Stadium ['Royal Challengers Bangalore'] 2 46 3
Punjab Cricket Association Stadium, Mohali ['Chennai Super Kings'] 1 42 1
Punjab Cricket Association Stadium, Mohali ['Kings XI Punjab'] 2 63 0
Wankhede Stadium ['Kolkata Knight Riders'] 1 49 0
Wankhede Stadium ['Mumbai Indians'] 2 46 0
MA Chidambaram Stadium ['Chennai Super Kings'] 1 32 3
MA Chidambaram Stadium ['Mumbai Indians'] 2 42 2
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium ['Sunrisers Hyderabad'] 1 54 1
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium ['Delhi Capitals'] 2 54 0
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium ['Delhi Capitals'] 1 41 2
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium ['Chennai Super Kings'] 2 43 0
Rajiv Gandhi International Stadium ['Mumbai Indians'] 1 45 2
Rajiv Gandhi International Stadium ['Chennai Super Kings'] 2 53 1
Sheikh Zayed Stadium ['Mumbai Indians'] 1 51 2
Sheikh Zayed Stadium ['Chennai Super Kings'] 2 37 2
Dubai International Cricket Stadium ['Delhi Capitals'] 1 23 3
Dubai International Cricket Stadium ['Kings XI Punjab'] 2 30 3
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 1 53 0
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 2 50 1
Sharjah Cricket Stadium ['Rajasthan Royals'] 1 54 1
Sharjah Cricket Stadium ['Chennai Super Kings'] 2 52 0
Sheikh Zayed Stadium ['Mumbai Indians'] 1 59 1
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 2 35 2
Dubai International Cricket Stadium ['Delhi Capitals'] 1 36 0
Dubai International Cricket Stadium ['Chennai Super Kings'] 2 35 2
Dubai International Cricket Stadium ['Kings XI Punjab'] 1 50 0
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 2 36 3
Sheikh Zayed Stadium ['Sunrisers Hyderabad'] 1 40 1
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 2 50 2
Sharjah Cricket Stadium ['Kings XI Punjab'] 1 60 0
Sharjah Cricket Stadium ['Rajasthan Royals'] 2 69 1
Dubai International Cricket Stadium ['Kolkata Knight Riders'] 1 42 1
Dubai International Cricket Stadium ['Rajasthan Royals'] 2 37 2
Sheikh Zayed Stadium ['Sunrisers Hyderabad'] 1 38 0
Sheikh Zayed Stadium ['Delhi Capitals'] 2 36 1
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 1 59 0
Dubai International Cricket Stadium ['Mumbai Indians'] 2 39 2
Sheikh Zayed Stadium ['Mumbai Indians'] 1 41 2
Sheikh Zayed Stadium ['Kings XI Punjab'] 2 42 2
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 1 42 1
Dubai International Cricket Stadium ['Chennai Super Kings'] 2 34 3
Sheikh Zayed Stadium ['Rajasthan Royals'] 1 38 3
Sheikh Zayed Stadium ['Royal Challengers Bangalore'] 2 50 1
Sharjah Cricket Stadium ['Delhi Capitals'] 1 57 1
Sharjah Cricket Stadium ['Kolkata Knight Riders'] 2 53 1
Dubai International Cricket Stadium ['Kings XI Punjab'] 1 46 0
Dubai International Cricket Stadium ['Chennai Super Kings'] 2 55 0
Sharjah Cricket Stadium ['Mumbai Indians'] 1 48 2
Sharjah Cricket Stadium ['Sunrisers Hyderabad'] 2 55 1
Dubai International Cricket Stadium ['Delhi Capitals'] 1 63 0
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 2 40 3
Sheikh Zayed Stadium ['Mumbai Indians'] 1 57 1
Sheikh Zayed Stadium ['Rajasthan Royals'] 2 34 3
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 1 52 1
Sheikh Zayed Stadium ['Chennai Super Kings'] 2 56 1
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 1 58 0
Dubai International Cricket Stadium ['Kings XI Punjab'] 2 50 2
Sharjah Cricket Stadium ['Delhi Capitals'] 1 51 3
Sharjah Cricket Stadium ['Rajasthan Royals'] 2 42 1
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 1 25 2
Sheikh Zayed Stadium ['Kings XI Punjab'] 2 48 0
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 1 36 1
Dubai International Cricket Stadium ['Chennai Super Kings'] 2 31 2
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 1 26 1
Dubai International Cricket Stadium ['Rajasthan Royals'] 2 36 3
Sheikh Zayed Stadium ['Delhi Capitals'] 1 46 2
Sheikh Zayed Stadium ['Mumbai Indians'] 2 45 1
Sharjah Cricket Stadium ['Royal Challengers Bangalore'] 1 47 0
Sharjah Cricket Stadium ['Kolkata Knight Riders'] 2 41 1
Dubai International Cricket Stadium ['Chennai Super Kings'] 1 44 2
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 2 40 2
Dubai International Cricket Stadium ['Delhi Capitals'] 1 47 2
Dubai International Cricket Stadium ['Rajasthan Royals'] 2 55 2
Sharjah Cricket Stadium ['Royal Challengers Bangalore'] 1 57 1
Sharjah Cricket Stadium ['Kings XI Punjab'] 2 62 0
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 1 33 2
Sheikh Zayed Stadium ['Mumbai Indians'] 2 50 0
Sharjah Cricket Stadium ['Chennai Super Kings'] 1 39 1
Sharjah Cricket Stadium ['Delhi Capitals'] 2 41 2
Dubai International Cricket Stadium ['Rajasthan Royals'] 1 52 1
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 2 48 1
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 1 48 1
Sheikh Zayed Stadium ['Sunrisers Hyderabad'] 2 57 0
Dubai International Cricket Stadium ['Mumbai Indians'] 1 43 3
Dubai International Cricket Stadium ['Kings XI Punjab'] 2 52 1
Sheikh Zayed Stadium ['Chennai Super Kings'] 1 43 2
Sheikh Zayed Stadium ['Rajasthan Royals'] 2 26 3
Dubai International Cricket Stadium ['Delhi Capitals'] 1 53 1
Dubai International Cricket Stadium ['Kings XI Punjab'] 2 56 3
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 1 17 4
Sheikh Zayed Stadium ['Royal Challengers Bangalore'] 2 43 0
Dubai International Cricket Stadium ['Rajasthan Royals'] 1 47 1
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 2 56 2
Sharjah Cricket Stadium ['Chennai Super Kings'] 1 24 5
Sharjah Cricket Stadium ['Mumbai Indians'] 2 55 0
Sheikh Zayed Stadium ['Kolkata Knight Riders'] 1 36 2
Sheikh Zayed Stadium ['Delhi Capitals'] 2 32 2
Dubai International Cricket Stadium ['Kings XI Punjab'] 1 47 1
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 2 51 0
Sheikh Zayed Stadium ['Mumbai Indians'] 1 59 1
Sheikh Zayed Stadium ['Rajasthan Royals'] 2 62 2
Dubai International Cricket Stadium ['Royal Challengers Bangalore'] 1 46 1
Dubai International Cricket Stadium ['Chennai Super Kings'] 2 53 1
Sharjah Cricket Stadium ['Kolkata Knight Riders'] 1 54 3
Sharjah Cricket Stadium ['Kings XI Punjab'] 2 37 0
Dubai International Cricket Stadium ['Sunrisers Hyderabad'] 1 77 0
Dubai International Cricket Stadium ['Delhi Capitals'] 2 48 2
Sheikh Zayed Stadium ['Royal Challengers Bangalore'] 1 54 0
Sheikh Zayed Stadium ['Mumbai Indians'] 2 44 1
Dubai International Cricket Stadium ['Kolkata Knight Riders'] 1 48 0
Dubai International Cricket Stadium ['Chennai Super Kings'] 2 39 0
Sheikh Zayed Stadium ['Kings XI Punjab'] 1 53 1
Sheikh Zayed Stadium ['Rajasthan Royals'] 2 70 1
Sharjah Cricket Stadium ['Royal Challengers Bangalore'] 1 30 2
Sharjah Cricket Stadium ['Sunrisers Hyderabad'] 2 56 1
Sheikh Zayed Stadium ['Royal Challengers Bangalore'] 1 40 1
Sheikh Zayed Stadium ['Delhi Capitals'] 2 52 1
Sheikh Zayed Stadium ['Kings XI Punjab'] 1 53 1
Sheikh Zayed Stadium ['Chennai Super Kings'] 2 48 0
Dubai International Cricket Stadium ['Kolkata Knight Riders'] 1 55 1
Dubai International Cricket Stadium ['Rajasthan Royals'] 2 40 5
Dubai International Cricket Stadium ['Delhi Capitals'] 1 22 2
Dubai International Cricket Stadium ['Mumbai Indians'] 2 39 0
Sharjah Cricket Stadium ['Mumbai Indians'] 1 48 2
Sharjah Cricket Stadium ['Sunrisers Hyderabad'] 2 54 0
Dubai International Cricket Stadium ['Mumbai Indians'] 1 63 1
Dubai International Cricket Stadium ['Delhi Capitals'] 2 33 4
Sheikh Zayed Stadium ['Royal Challengers Bangalore'] 1 32 2
Sheikh Zayed Stadium ['Sunrisers Hyderabad'] 2 40 2
Sheikh Zayed Stadium ['Delhi Capitals'] 1 65 0
Sheikh Zayed Stadium ['Sunrisers Hyderabad'] 2 48 3
Dubai International Cricket Stadium ['Delhi Capitals'] 1 41 3
Dubai International Cricket Stadium ['Mumbai Indians'] 2 57 1

In [ ]:
features

    match_id                                venue  ... ppruns wickets
0    1175356               MA Chidambaram Stadium  ...     33       2
1    1175356               MA Chidambaram Stadium  ...     17       1
2    1175357                         Eden Gardens  ...     54       0
3    1175357                         Eden Gardens  ...     51       1
4    1175358                     Wankhede Stadium  ...     45       2
..       ...                                  ...  ...    ...     ...
355  1237178                 Sheikh Zayed Stadium  ...     40       2
356  1237180                 Sheikh Zayed Stadium  ...     65       0
357  1237180                 Sheikh Zayed Stadium  ...     48       3
358  1237181  Dubai International Cricket Stadium  ...     41       3
359  1237181  Dubai International Cricket Stadium  ...     57       1

[360 rows x 9 columns]

In [ ]:
features[(features['venue']=='MA Chidambaram Stadium') & (features['innings']==2)]['ppruns'].sum()#['ppruns'].sum()

415

In [ ]:
chennai = 2793/59

In [ ]:
chennai

47.33898305084746

In [ ]:
venues=features['venue'].unique()

In [ ]:
for j in venues:
  pruns=features[(features['venue']==j) & (features['innings']==1)]['ppruns'].sum()
  matches=len(features[(features['venue']==j) & (features['innings']==1)]['ppruns'])
  venue1ind=pruns/matches
  pruns1=features[(features['venue']==j) & (features['innings']==2)]['ppruns'].sum()
  matches1=len(features[(features['venue']==j) & (features['innings']==2)]['ppruns'])
  venue2ind=pruns1/matches1
  print(j,pruns,matches,venue1ind,pruns1,matches1,venue2ind)

MA Chidambaram Stadium 367 9 40.77777777777778 415 9 46.111111111111114
Eden Gardens 785 16 49.0625 854 16 53.375
Wankhede Stadium 1101 22 50.04545454545455 1051 22 47.77272727272727
Sawai Mansingh Stadium 655 14 46.785714285714285 738 14 52.714285714285715
Arun Jaitley Stadium 648 14 46.285714285714285 756 14 54.0
M Chinnaswamy Stadium 687 14 49.07142857142857 667 14 47.642857142857146
Rajiv Gandhi International Stadium 723 15 48.2 807 15 53.8
Punjab Cricket Association Stadium, Mohali 494 10 49.4 532 10 53.2
Holkar Cricket Stadium 200 4 50.0 200 4 50.0
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium 95 2 47.5 97 2 48.5
Sheikh Zayed Stadium 980 22 44.54545454545455 1005 22 45.68181818181818
Dubai International Cricket Stadium 1219 26 46.88461538461539 1140 26 43.84615384615385
Sharjah Cricket Stadium 569 12 47.416666666666664 617 12 51.416666666666664